.nr PS 12p
.EQ
delim $$
.EN
.
.
.LP
.ce
\fBCSCI 3355 Software Design and Construction\fR
.
.LP
.ce
\fBLab Document\fR
.
.
.TS H
allbox tab(#);
Lb Lx.
.TH
High-level Purpose statement:#T{
I want to get a feel for how the nodejs framework works.
T}
.
Experiment Design:#T{
I will make a couple of simple nodejs projects that use several features of them.
T}
.
Resources Available:#T{
Nodejs documentation is the most important.
T}
.
Time estimate:#T{
A couple of hours.
T}
.
Experiment Notes:#T{
It feels weird calling javascript a backend language.
I first made the obligiatory \(cqHello World\(cq project.
Next as I was running low on time I moved onto looking into node\(cqs rest ablities.
It looks like it may provide some explicit rest capablities with express,
but it also provides the ablitly to get an URL,
which is plenty enough to build some rest stuff.
Since I am in javascript,
I can switch on strings.
(that feels too weird).
Using that I built something that could later be built to be restful.
T}
.
Results:#T{
I have a basic understanding of nodejs.
And a few files that could later be built out to be something more.
T}
.
Consequences for the Future:#T{
It in a way feels like the web server part of libevent.
It could be interesting to compare the two.
T}
.TE
.

