.nr PS 12p
.EQ
delim $$
.EN
.
.
.LP
.ce
\fBCSCI 3355 Software Design and Construction\fR
.
.LP
.ce
\fBLab Document\fR
.
.
.TS H
allbox tab(#);
Lb Lx.
.TH
High-level Purpose statement:#T{
I would like to get a futher feel for the nodejs framework.
T}
.
Experiment Design:#T{
I\(cqll try to make something that uses the nodejs framework.
T}
.
Resources Available:#T{
Nodejs documentation is the most important.
T}
.
Time estimate:#T{
Not long enough.
I have been debugging an lalr parser all week for programing langs,
and now apparently have to do the final project for OS on my own.
What is sleep?
T}
.
Experiment Notes:#T{
I didn\cqt have enough time to do this.
I made some slightly more complicate rest.
I brought back the buttons from my spring lab.
After figuring out that I have to explicitly read the file as utf-8,
I was able to serve a page that update when posted to.
T}
.
Results:#T{
I now have a page that can be posted to for updating it.
T}
.
Consequences for the Future:#T{
Nodejs will certianly stay in my bag of tricks.
T}
.TE
.

